package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.BikePathStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a bike path in the BBP system.
 * Bike paths can be inserted manually or automatically through GPS tracking.
 * Contains route information, status assessment, and associated obstacles.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BikePath {

    /**
     * The unique identifier for the bike path.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Version number for optimistic locking.
     * Used to prevent concurrent modification conflicts.
     */
    @Version
    @Column(nullable = false)
    private Long version;

    /**
     * The user who originally created this bike path.
     * This field is required and establishes the ownership of the bike path.
     */
    @ManyToOne
    @JoinColumn(name = "created_by_id", nullable = false)
    @NotNull(message = "User is required")
    private User createdBy;

    /**
     * The date and time when this bike path was created.
     * This field is required.
     */
    @Column(nullable = false)
    @NotNull(message = "Creation date is required")
    private OffsetDateTime createdAt;

    /**
     * The user who last updated this bike path.
     * This field is optional and is set to null if the user who updated it is deleted.
     */
    @ManyToOne
    @JoinColumn(name = "updated_by_id", nullable = true, foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (updated_by_id) REFERENCES users(id) ON DELETE SET NULL"))
    private User updatedBy;

    /**
     * The date and time of the last update to this bike path.
     * This field is optional and is null if the path has never been updated.
     */
    @Column(nullable = true)
    private OffsetDateTime updatedAt;

    /**
     * The name or address of the bike path's starting point.
     * This field is required and cannot exceed 255 characters.
     */
    @Column(nullable = false, length = 255)
    @NotBlank(message = "Origin is required")
    @Size(max = 255, message = "Origin must not exceed 255 characters")
    private String origin;

    /**
     * The latitude coordinate of the origin point.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of origin is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double originLatitude;

    /**
     * The longitude coordinate of the origin point.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of origin is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double originLongitude;

    /**
     * The name or address of the bike path's destination point.
     * This field is required and cannot exceed 255 characters.
     */
    @Column(nullable = false, length = 255)
    @NotBlank(message = "Destination is required")
    @Size(max = 255, message = "Destination must not exceed 255 characters")
    private String destination;

    /**
     * The latitude coordinate of the destination point.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of destination is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double destinationLatitude;

    /**
     * The longitude coordinate of the destination point.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of destination is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double destinationLongitude;

    /**
     * An optional description or notes about the bike path.
     * Maximum length is 500 characters.
     */
    @Column(nullable = true, length = 500)
    @Size(max = 500, message = "Description must not exceed 500 characters")
    private String description;

    /**
     * The overall quality score of the bike path.
     * This field is required and must be between 0.0 and 5.0.
     * The score is computed based on the path status and effectiveness.
     * Precision: 3 digits total, 2 after the decimal point (e.g., 4.75).
     */
    @Column(nullable = false, precision = 3, scale = 2)
    @NotNull(message = "Score is required")
    @DecimalMin(value = "0.0", message = "Score must be at least 0.0")
    @DecimalMax(value = "5.0", message = "Score must be at most 5.0")
    private BigDecimal score;

    /**
     * The current condition status of the bike path.
     * This field is required and indicates the maintenance level and usability.
     * Possible values include: EXCELLENT, GOOD, SUFFICIENT, POOR, UNDER_MAINTENANCE, etc.
     */
    @Column(nullable = false, length = 25)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Status is required")
    private BikePathStatus status;

    /**
     * The total distance of the bike path in kilometers.
     * This field is required and must be greater than 0.
     * Precision: 8 digits total, 3 after the decimal point (e.g., 12345.678).
     */
    @Column(nullable = false, precision = 8, scale = 3)
    @NotNull(message = "Total distance is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Total distance must be greater than 0")
    private BigDecimal totalDistance;

    /**
     * Flag indicating whether this bike path is published and visible to all users.
     * This field is required.
     * When false, the path is only visible to its creator.
     */
    @Column(nullable = false)
    @NotNull(message = "Publishable flag is required")
    private Boolean published;

    /**
     * The collection of GPS coordinate points that define the bike path route.
     * Each point represents a specific location along the path.
     * When a bike path is deleted, all associated points are also removed (cascade delete).
     */
    @OneToMany(mappedBy = "bikePath",  cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<BikePathPoint> bikePathPoints = new ArrayList<>();

    /**
     * The collection of obstacles reported along this bike path.
     * Obstacles include issues like potholes or other problems affecting the route.
     * When a bike path is deleted, all associated obstacles are also removed (cascade delete).
     */
    @OneToMany(mappedBy = "bikePath",  cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Obstacle> obstacles = new ArrayList<>();

}