package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.BikePathStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.*;

/**
 * Entity representing a bike path in the system.
 * Can be inserted manually or through GPS tracking.
 * Contains route information, status, score, and associated obstacles.
 */
@Entity
@Table
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"bikePathPoints", "obstacles"})
public class BikePath {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bike_path_generator")
    @SequenceGenerator(name = "bike_path_generator", sequenceName = "bike_path_sequence", allocationSize = 1)
    private Long id;

    /**
     * Version number for optimistic locking to prevent concurrent modification conflicts.
     */
    @Version
    @Column(nullable = false)
    private Long version;

    /**
     * User who originally created this bike path.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_id", nullable = false)
    @NotNull(message = "User is required")
    private User createdBy;

    /**
     * Creation timestamp.
     */
    @Column(nullable = false)
    @NotNull(message = "Creation date is required")
    private OffsetDateTime createdAt;

    /**
     * User who last updated this bike path.
     * Null if never updated or if user was deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updated_by_id", nullable = true,
            foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (updated_by_id) REFERENCES users(id) ON DELETE SET NULL"))
    private User updatedBy;

    /**
     * Last update timestamp.
     * Null if never updated.
     */
    @Column(nullable = true)
    private OffsetDateTime updatedAt;

    /**
     * Name or address of starting point.
     * Maximum 256 characters.
     */
    @Column(nullable = false, length = 256)
    @NotBlank(message = "Origin is required")
    @Size(max = 256, message = "Origin must not exceed 256 characters")
    private String origin;

    /**
     * Latitude coordinate of origin point.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of origin is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double originLatitude;

    /**
     * Longitude coordinate of origin point.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of origin is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double originLongitude;

    /**
     * Name or address of destination point.
     * Maximum 256 characters.
     */
    @Column(nullable = false, length = 256)
    @NotBlank(message = "Destination is required")
    @Size(max = 256, message = "Destination must not exceed 256 characters")
    private String destination;

    /**
     * Latitude coordinate of destination point.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of destination is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double destinationLatitude;

    /**
     * Longitude coordinate of destination point.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of destination is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double destinationLongitude;

    /**
     * Optional description or notes.
     * Maximum 500 characters.
     */
    @Column(nullable = true, length = 500)
    @Size(max = 500, message = "Description must not exceed 500 characters")
    private String description;

    /**
     * Overall quality score.
     * Range: 0.0 to 5.0, computed from status and obstacles.
     * Precision: 3 digits total, 2 decimal (e.g., 4.75).
     */
    @Column(nullable = false, precision = 3, scale = 2)
    @NotNull(message = "Score is required")
    @DecimalMin(value = "0.0", message = "Score must be at least 0.0")
    @DecimalMax(value = "5.0", message = "Score must be at most 5.0")
    private BigDecimal score;

    /**
     * Current condition status indicating maintenance level and usability.
     */
    @Column(nullable = false, length = 25)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Status is required")
    private BikePathStatus status;

    /**
     * Total distance in kilometers.
     * Must be greater than 0.
     * Precision: 8 digits total, 3 decimal (e.g., 12345.678).
     */
    @Column(nullable = false, precision = 8, scale = 3)
    @NotNull(message = "Total distance is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Total distance must be greater than 0")
    private BigDecimal totalDistance;

    /**
     * Visibility flag.
     * False = visible only to creator.
     * True = visible to all users.
     */
    @Column(nullable = false)
    @NotNull(message = "Publishable flag is required")
    private Boolean published;

    /**
     * GPS coordinate points defining the bike path route.
     * Cascade delete: removed when bike path is deleted.
     */
    @OneToMany(mappedBy = "bikePath", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("sequentialPosition ASC")
    @Builder.Default
    private List<BikePathPoint> bikePathPoints = new ArrayList<>();

    /**
     * Obstacles reported along this bike path.
     * Cascade delete: removed when bike path is deleted.
     */
    @OneToMany(mappedBy = "bikePath", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("positionOnPath ASC")
    @Builder.Default
    private List<Obstacle> obstacles = new ArrayList<>();

    /**
     * Adds a coordinate point and synchronizes bidirectional relationship.
     * @param point bike path point to add
     */
    public void addBikePathPoint(BikePathPoint point) {
        if (this.bikePathPoints == null) {
            this.bikePathPoints = new ArrayList<>();
        }
        this.bikePathPoints.add(point);
        point.setBikePath(this);
    }

    /**
     * Removes a coordinate point and synchronizes bidirectional relationship.
     * @param point bike path point to remove
     */
    public void removeBikePathPoint(BikePathPoint point) {
        if (this.bikePathPoints != null) {
            this.bikePathPoints.remove(point);
            point.setBikePath(null);
        }
    }

    /**
     * Adds an obstacle and synchronizes bidirectional relationship.
     * @param obstacle obstacle to add
     */
    public void addObstacle(Obstacle obstacle) {
        if (this.obstacles == null) {
            this.obstacles = new ArrayList<>();
        }
        this.obstacles.add(obstacle);
        obstacle.setBikePath(this);
    }

    /**
     * Removes an obstacle and synchronizes bidirectional relationship.
     * @param obstacle obstacle to remove
     */
    public void removeObstacle(Obstacle obstacle) {
        if (this.obstacles != null) {
            this.obstacles.remove(obstacle);
            obstacle.setBikePath(null);
        }
    }

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        BikePath bikePath = (BikePath) o;
        return getId() != null && Objects.equals(getId(), bikePath.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}