package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.openmeteo.WeatherCondition;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.util.Objects;

/**
 * Entity representing meteorological data associated with a trip.
 * Retrieved from external weather service when available.
 * Provides weather context for analyzing trip performance and conditions.
 */
@Entity
@Table
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = "trip")
public class MeteorologicalData {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "meteorological_data_generator")
    @SequenceGenerator(name = "meteorological_data_generator", sequenceName = "meteorological_data_sequence", allocationSize = 1)
    private Long id;

    /**
     * Parent trip to which this meteorological data belongs.
     * One-to-one relationship.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id", nullable = false)
    @NotNull(message = "Trip is required")
    private Trip trip;

    /**
     * General weather condition during the trip.
     */
    @Column(nullable = false, length = 30)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Weather condition is required")
    private WeatherCondition weatherCondition;

    /**
     * Ambient temperature in degrees Celsius.
     * Range: -99.9 to +99.9 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Temperature is required")
    @DecimalMin(value = "-99.9", message = "Temperature must be between -99.9 and +99.9")
    @DecimalMax(value = "99.9", message = "Temperature must be between -99.9 and +99.9")
    private Double temperature;

    /**
     * Relative humidity as percentage.
     * Range: 0 to 100.
     */
    @Column(nullable = false)
    @NotNull(message = "Humidity is required")
    @Min(value = 0, message = "Humidity cannot be less than 0")
    @Max(value = 100, message = "Humidity cannot be higher than 100")
    private Integer humidity;

    /**
     * Wind speed in km/h.
     * Range: 0.0 to 999.9.
     */
    @Column(nullable = false)
    @NotNull(message = "Wind speed is required")
    @DecimalMin(value = "0.0", message = "Wind speed cannot be less than 0.0")
    @DecimalMax(value = "999.9", message = "Wind speed cannot be higher than 999.9")
    private Double windSpeed;

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        MeteorologicalData that = (MeteorologicalData) o;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}