package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.openmeteo.WeatherCondition;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing meteorological data associated with a trip.
 * This data is retrieved from an external weather service when available.
 * Provides weather context for analyzing trip performance and conditions.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MeteorologicalData {

    /**
     * The unique identifier for the meteorological data record.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The trip to which this meteorological data belongs.
     * This field is required and establishes a one-to-one relationship with the trip.
     */
    @OneToOne
    @JoinColumn(name = "trip_id", nullable = false)
    @NotNull
    private Trip trip;

    /**
     * The general weather condition during the trip.
     * This field is required and describes the overall weather state.
     */
    @Column(nullable = false, length = 30)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Weather condition is required")
    private WeatherCondition weatherCondition;

    /**
     * The ambient temperature during the trip in degrees Celsius.
     * This field is required and must be between -99.9 and +99.9 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Temperature is required")
    @DecimalMin(value = "-99.9", message = "Temperature must be between -99.9 and +99.9")
    @DecimalMax(value = "99.9", message = "Temperature must be between -99.9 and +99.9")
    private Double temperature;

    /**
     * The relative humidity during the trip as a percentage.
     * This field is required and must be between 0 and 100.
     */
    @Column(nullable = false)
    @NotNull(message = "Humidity is required")
    @Min(value = 0, message = "Humidity cannot be less than 0")
    @Max(value = 100, message = "Humidity cannot be higher than 100")
    private Integer humidity;

    /**
     * The wind speed during the trip in km/h.
     * This field is required and must be between 0.0 and 999.9.
     */
    @Column(nullable = false)
    @NotNull(message = "Wind speed is required")
    @DecimalMin(value = "0.0", message = "Wind speed cannot be less than 0.0")
    @DecimalMax(value = "999.9", message = "Wind speed cannot be higher than 999.9")
    private Double windSpeed;

}