package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.ObstacleSeverity;
import it.polimi.se.bbp.enums.ObstacleType;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Entity representing an obstacle on a bike path.
 * Includes issues like potholes or other problems affecting cycling safety.
 * Can be reported manually by users or detected automatically.
 */
@Entity
@Table
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = "bikePath")
public class Obstacle {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "obstacle_generator")
    @SequenceGenerator(name = "obstacle_generator", sequenceName = "obstacle_sequence", allocationSize = 5)
    private Long id;

    /**
     * Parent bike path where this obstacle is located.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bike_path_id", nullable = false)
    @NotNull(message = "Bike path is required")
    private BikePath bikePath;

    /**
     * User who reported this obstacle.
     * Null if user deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_id", nullable = true,
            foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL"))
    private User createdBy;

    /**
     * Creation timestamp.
     */
    @Column(nullable = false)
    @NotNull(message = "Creation date is required")
    private OffsetDateTime createdAt;

    /**
     * User who last updated this obstacle.
     * Null if never updated or user deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updated_by_id", nullable = true,
            foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (updated_by_id) REFERENCES users(id) ON DELETE SET NULL"))
    private User updatedBy;

    /**
     * Last update timestamp.
     * Null if never updated.
     */
    @Column(nullable = true)
    private OffsetDateTime updatedAt;

    /**
     * Address or location description of the obstacle.
     * Maximum 256 characters.
     */
    @Column(nullable = false, length = 256)
    @NotBlank(message = "Address is required")
    @Size(max = 256, message = "Address must not exceed 256 characters")
    private String address;

    /**
     * Latitude coordinate.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double latitude;

    /**
     * Longitude coordinate.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double longitude;

    /**
     * Type or category of the obstacle.
     * Examples: POTHOLE, DEBRIS, CONSTRUCTION.
     */
    @Column(nullable = false, length = 25)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Type is required")
    private ObstacleType type;

    /**
     * Severity level of the obstacle.
     * Possible values: LOW, MEDIUM, HIGH, CRITICAL.
     */
    @Column(nullable = false, length = 15)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Severity is required")
    private ObstacleSeverity severity;

    /**
     * Active status flag.
     * False = resolved or no longer present.
     */
    @Column(nullable = false)
    @NotNull(message = "Active flag is required")
    private Boolean active;

    /**
     * Position of obstacle along the bike path route.
     * Must be at least 0.
     */
    @Column(nullable = false)
    @NotNull(message = "Position on path is required")
    @Min(value = 0, message = "Position on path must be at least 0")
    private Integer positionOnPath;

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        Obstacle obstacle = (Obstacle) o;
        return getId() != null && Objects.equals(getId(), obstacle.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}