package it.polimi.se.bbp.entity;

import it.polimi.se.bbp.enums.ObstacleType;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity class representing an obstacle on a bike path in the BBP system.
 * Obstacles include issues like potholes or other problems that affect cycling safety.
 * Can be reported manually by users or detected automatically through accelerometer and gyroscope data.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Obstacle {

    /**
     * The unique identifier for the obstacle.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Version number for optimistic locking.
     * Used to prevent concurrent modification conflicts.
     */
    @Version
    @Column(nullable = false)
    private Long version;

    /**
     * The bike path where this obstacle is located.
     * This field is required and establishes the relationship with the affected bike path.
     */
    @ManyToOne
    @JoinColumn(name = "bike_path_id", nullable = false)
    @NotNull(message = "Bike path is required")
    private BikePath bikePath;

    /**
     * The user who originally reported or created this obstacle record.
     * This field is optional and is set to null if the user who created it is deleted.
     */
    @ManyToOne
    @JoinColumn(name = "created_by_id", nullable = true, foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (created_by_id) REFERENCES user(id) ON DELETE SET NULL"))
    private User createdBy;

    /**
     * The date and time when this obstacle was first reported.
     * This field is required.
     */
    @Column(nullable = false)
    @NotNull(message = "Creation date is required")
    private LocalDateTime createdAt;

    /**
     * The user who last updated this obstacle record.
     * This field is optional and is set to null if the user who updated it is deleted.
     */
    @ManyToOne
    @JoinColumn(name = "updated_by_id", nullable = true, foreignKey = @ForeignKey(foreignKeyDefinition = "FOREIGN KEY (updated_by_id) REFERENCES user(id) ON DELETE SET NULL"))
    private User updatedBy;

    /**
     * The date and time of the last update to this obstacle record.
     * This field is optional and is null if the obstacle has never been updated.
     */
    @Column(nullable = true)
    private LocalDateTime updatedAt;

    /**
     * The name or description of the location where the obstacle is present.
     * This field is required and cannot exceed 255 characters.
     */
    @Column(nullable = false, length = 255)
    @NotBlank(message = "Location is required")
    @Size(max = 255, message = "Location must not exceed 255 characters")
    private String location;

    /**
     * The latitude coordinate of the obstacle's location.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double latitude;

    /**
     * The longitude coordinate of the obstacle's location.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double longitude;

    /**
     * The type or category of the obstacle.
     * This field is required and describes the nature of the problem.
     * Possible values include: POTHOLE, DEBRIS, CONSTRUCTION, etc.
     */
    @Column(nullable = false, length = 25)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Type is required")
    private ObstacleType type;

    /**
     * The severity level of the obstacle.
     * This field is required and indicates how serious the problem is.
     * Possible values include: LOW, MEDIUM, HIGH, CRITICAL.
     */
    @Column(nullable = false, length = 15)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Severity is required")
    private ObstacleType severity;

    /**
     * Flag indicating whether this obstacle is currently active and present.
     * This field is required.
     * When false, the obstacle has been resolved or is no longer present.
     */
    @Column(nullable = false)
    @NotNull(message = "Active flag is required")
    private Boolean is_active;

}