package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a cycling trip recorded by a user in the BBP system.
 * Contains information about the route, timing, performance metrics, and optional meteorological data.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Trip {

    /**
     * The unique identifier for the trip.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who recorded this trip.
     * This field is required and establishes the ownership of the trip.
     */
    @ManyToOne
    @JoinColumn(name = "recorded_by_id", nullable = false)
    @NotNull(message = "User is required")
    private User recordedBy;

    /**
     * The name or address of the trip's starting point.
     * This field is required and cannot exceed 255 characters.
     */
    @Column(nullable = false, length = 255)
    @NotBlank(message = "Origin is required")
    @Size(max = 255, message = "Origin must not exceed 255 characters")
    private String origin;

    /**
     * The latitude coordinate of the origin point.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of origin is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double originLatitude;

    /**
     * The longitude coordinate of the origin point.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of origin is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double originLongitude;

    /**
     * The name or address of the trip's destination point.
     * This field is required and cannot exceed 255 characters.
     */
    @Column(nullable = false, length = 255)
    @NotBlank(message = "Destination is required")
    @Size(max = 255, message = "Destination must not exceed 255 characters")
    private String destination;

    /**
     * The latitude coordinate of the destination point.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of destination is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double destinationLatitude;

    /**
     * The longitude coordinate of the destination point.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of destination is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double destinationLongitude;

    /**
     * An optional description or notes about the trip.
     * Maximum length is 500 characters.
     */
    @Column(nullable = true, length = 500)
    @Size(max = 500, message = "Description must not exceed 500 characters")
    private String description;

    /**
     * The exact date and time when the trip started.
     * This field is required.
     */
    @Column(nullable = false)
    @NotNull(message = "Start time is required")
    private OffsetDateTime startTime;

    /**
     * The exact date and time when the trip ended.
     * This field is required and must be after the start time.
     */
    @Column(nullable = false)
    @NotNull(message = "End time is required")
    private OffsetDateTime endTime;

    /**
     * The total duration of the trip in minutes.
     * This field is required and must be at least 1 minute.
     */
    @Column(nullable = false)
    @NotNull(message = "Total duration cannot be null")
    @Min(value = 1, message = "Total duration must be at least 1 minute")
    private Integer totalDuration;

    /**
     * The total distance covered during the trip in kilometers.
     * This field is required and must be greater than 0.
     * Precision: 8 digits total, 3 after the decimal point (e.g., 12345.678).
     */
    @Column(nullable = false, precision = 8, scale = 3)
    @NotNull(message = "Total distance is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Total distance must be greater than 0")
    private BigDecimal totalDistance;

    /**
     * The average speed maintained during the trip in km/h.
     * This field is required and must be greater than 0.
     * Precision: 5 digits total, 2 after the decimal point (e.g., 123.45).
     */
    @Column(nullable = false, precision = 5, scale = 2)
    @NotNull(message = "Average speed is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Average speed must be greater than 0")
    private BigDecimal averageSpeed;

    /**
     * The maximum speed reached during the trip in km/h.
     * This field must be greater than 0, and must be greater than or equal to the average speed.
     * Precision: 5 digits total, 2 after the decimal point (e.g., 123.45).
     */
    @Column(nullable = true, precision = 5, scale = 2)
    @DecimalMin(value = "0.0", inclusive = false, message = "Max speed must be greater than 0")
    private BigDecimal maxSpeed;

    /**
     * Optional meteorological data associated with this trip.
     * Contains weather conditions, temperature, wind speed, and humidity retrieved from an external service.
     * When a trip is deleted, the associated meteorological data is also removed (cascade delete).
     */
    @OneToOne(mappedBy = "trip", optional = true, cascade = CascadeType.ALL, orphanRemoval = true)
    private MeteorologicalData meteorologicalData;

    /**
     * The collection of GPS coordinates recorded during the trip.
     * Each point represents a specific location along the route with its timestamp.
     * When a trip is deleted, all associated trip points are also removed (cascade delete).
     */
    @OneToMany(mappedBy = "trip", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<TripPoint> tripPoints = new ArrayList<>();

    /**
     * Validates that the end time is after the start time.
     * This validation ensures the temporal consistency of the trip.
     * @return true if end time is after start time, false otherwise
     */
    @AssertTrue(message = "End time must be after start time")
    private boolean isEndTimeAfterStartTime() {
        if (startTime == null || endTime == null)
            return true;
        return endTime.isAfter(startTime);
    }

    /**
     * Validates that the trip duration is at least 1 minute.
     * This validation prevents the recording of unrealistically short trips.
     * @return true if the trip duration is at least 1 minute, false otherwise
     */
    @AssertTrue(message = "Trip must be at least 1 minute long")
    private boolean isTripTotalDurationValid() {
        if (startTime == null || endTime == null)
            return true;
        return Duration.between(startTime, endTime).toMinutes() >= 1;
    }

    /**
     * Validates that the maximum speed is greater than or equal to the average speed.
     * This validation ensures logical consistency in speed metrics.
     * @return true if max speed is greater than or equal to average speed, false otherwise
     */
    @AssertTrue(message = "Max speed must be greater than or equal to average speed")
    private boolean isMaxSpeedGreaterThanAverageSpeed() {
        if (averageSpeed == null || maxSpeed == null)
            return true;
        return maxSpeed.compareTo(averageSpeed) >= 0;
    }

}