package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Entity representing a GPS coordinate point recorded during a trip.
 * Points are used to reconstruct the complete route followed by the user.
 */
@Entity
@Table
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = "trip")
public class TripPoint {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "trip_point_generator")
    @SequenceGenerator(name = "trip_point_generator", sequenceName = "trip_point_sequence", allocationSize = 50)
    private Long id;

    /**
     * Parent trip to which this GPS point belongs.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id", nullable = false)
    @NotNull(message = "Trip is required")
    private Trip trip;

    /**
     * Latitude coordinate.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double latitude;

    /**
     * Longitude coordinate.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double longitude;

    /**
     * Timestamp when this GPS point was recorded.
     * Optional, null for manually recorded trips.
     */
    @Column(nullable = true)
    private OffsetDateTime timestamp;

    /**
     * Sequential position in the trip route.
     * Must be at least 1, lower values indicate earlier points.
     */
    @Column(nullable = false)
    @NotNull(message = "Sequential position is required")
    @Min(value = 1, message = "Sequential position must be at least 1")
    private Integer sequentialPosition;

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        TripPoint tripPoint = (TripPoint) o;
        return getId() != null && Objects.equals(getId(), tripPoint.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}