package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * Entity class representing a GPS coordinate point recorded during a trip.
 * Trip points are used to reconstruct the complete route followed by the user.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TripPoint {

    /**
     * The unique identifier for the trip point.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The trip to which this GPS point belongs.
     * This field is required and establishes the relationship with the parent trip.
     */
    @ManyToOne
    @JoinColumn(name = "trip_id", nullable = false)
    @NotNull(message = "Trip is required")
    private Trip trip;

    /**
     * The latitude coordinate of this GPS point.
     * This field is required and must be between -90 and +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double latitude;

    /**
     * The longitude coordinate of this GPS point.
     * This field is required and must be between -180 and +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double longitude;

    /**
     * The exact date and time when this GPS point was recorded.
     * This field is optional.
     */
    @Column(nullable = true)
    private OffsetDateTime timestamp;

    /**
     * The sequential position of this point in the trip route.
     * This field is required and must be at least 1.
     * Lower values indicate earlier points in the trip.
     */
    @Column(nullable = false)
    @NotNull(message = "Sequential position is required")
    @Min(value = 1, message = "Sequential position must be at least 1")
    private Integer sequentialPosition;

}