package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.*;

/**
 * Entity representing a cycling trip recorded by a user.
 * Contains route, timing, performance metrics, and optional meteorological data.
 */
@Entity
@Table
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"meteorologicalData", "tripPoints"})
public class Trip {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "trip_generator")
    @SequenceGenerator(name = "trip_generator", sequenceName = "trip_sequence", allocationSize = 1)
    private Long id;

    /**
     * User who recorded this trip.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recorded_by_id", nullable = false)
    @NotNull(message = "User is required")
    private User recordedBy;

    /**
     * Name or address of starting point.
     * Maximum 256 characters.
     */
    @Column(nullable = false, length = 256)
    @NotBlank(message = "Origin is required")
    @Size(max = 256, message = "Origin must not exceed 256 characters")
    private String origin;

    /**
     * Latitude coordinate of origin point.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of origin is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double originLatitude;

    /**
     * Longitude coordinate of origin point.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of origin is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double originLongitude;

    /**
     * Name or address of destination point.
     * Maximum 256 characters.
     */
    @Column(nullable = false, length = 256)
    @NotBlank(message = "Destination is required")
    @Size(max = 256, message = "Destination must not exceed 256 characters")
    private String destination;

    /**
     * Latitude coordinate of destination point.
     * Range: -90 to +90 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Latitude of destination is required")
    @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and +90")
    @DecimalMax(value = "90.0", message = "Latitude must be between -90 and +90")
    private Double destinationLatitude;

    /**
     * Longitude coordinate of destination point.
     * Range: -180 to +180 degrees.
     */
    @Column(nullable = false)
    @NotNull(message = "Longitude of destination is required")
    @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and +180")
    @DecimalMax(value = "180.0", message = "Longitude must be between -180 and +180")
    private Double destinationLongitude;

    /**
     * Optional description or notes.
     * Maximum 500 characters.
     */
    @Column(nullable = true, length = 500)
    @Size(max = 500, message = "Description must not exceed 500 characters")
    private String description;

    /**
     * Start timestamp.
     */
    @Column(nullable = false)
    @NotNull(message = "Start time is required")
    private OffsetDateTime startTime;

    /**
     * End timestamp.
     * Must be after start time.
     */
    @Column(nullable = false)
    @NotNull(message = "End time is required")
    private OffsetDateTime endTime;

    /**
     * Total duration in minutes.
     * Must be at least 1 minute.
     */
    @Column(nullable = false)
    @NotNull(message = "Total duration cannot be null")
    @Min(value = 1, message = "Total duration must be at least 1 minute")
    private Integer totalDuration;

    /**
     * Total distance in kilometers.
     * Must be greater than 0.
     * Precision: 8 digits total, 3 decimal (e.g., 12345.678).
     */
    @Column(nullable = false, precision = 8, scale = 3)
    @NotNull(message = "Total distance is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Total distance must be greater than 0")
    private BigDecimal totalDistance;

    /**
     * Average speed in km/h.
     * Must be greater than 0.
     * Precision: 5 digits total, 2 decimal (e.g., 123.45).
     */
    @Column(nullable = false, precision = 5, scale = 2)
    @NotNull(message = "Average speed is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Average speed must be greater than 0")
    private BigDecimal averageSpeed;

    /**
     * Maximum speed in km/h.
     * Optional, must be greater than 0 and >= average speed when provided.
     * Precision: 5 digits total, 2 decimal (e.g., 123.45).
     */
    @Column(nullable = true, precision = 5, scale = 2)
    @DecimalMin(value = "0.0", inclusive = false, message = "Max speed must be greater than 0")
    private BigDecimal maxSpeed;

    /**
     * Optional meteorological data.
     * Weather conditions, temperature, wind speed, and humidity.
     * Cascade delete: removed when trip is deleted.
     */
    @OneToOne(mappedBy = "trip", optional = true, cascade = CascadeType.ALL, orphanRemoval = true)
    private MeteorologicalData meteorologicalData;

    /**
     * GPS coordinates recorded during the trip.
     * Cascade delete: removed when trip is deleted.
     */
    @OneToMany(mappedBy = "trip", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("sequentialPosition ASC")
    @Builder.Default
    private List<TripPoint> tripPoints = new ArrayList<>();

    /**
     * Sets meteorological data and synchronizes bidirectional relationship.
     * @param meteorologicalData meteorological data to set
     */
    public void setMeteorologicalData(MeteorologicalData meteorologicalData) {
        if (meteorologicalData == null) {
            if (this.meteorologicalData != null)
                this.meteorologicalData.setTrip(null);
        } else {
            meteorologicalData.setTrip(this);
        }
        this.meteorologicalData = meteorologicalData;
    }

    /**
     * Adds a trip point and synchronizes bidirectional relationship.
     * @param tripPoint trip point to add
     */
    public void addTripPoint(TripPoint tripPoint) {
        if (this.tripPoints == null) {
            this.tripPoints = new ArrayList<>();
        }
        this.tripPoints.add(tripPoint);
        tripPoint.setTrip(this);
    }

    /**
     * Removes a trip point and synchronizes bidirectional relationship.
     * @param tripPoint trip point to remove
     */
    public void removeTripPoint(TripPoint tripPoint) {
        if (this.tripPoints != null) {
            this.tripPoints.remove(tripPoint);
            tripPoint.setTrip(null);
        }
    }

    /**
     * Validates that end time is after start time.
     * @return true if temporal consistency is valid
     */
    @AssertTrue(message = "End time must be after start time")
    public boolean isEndTimeAfterStartTime() {
        if (startTime == null || endTime == null)
            return true;
        return endTime.isAfter(startTime);
    }

    /**
     * Validates that trip duration is at least 1 minute.
     * @return true if duration is valid
     */
    @AssertTrue(message = "Trip must be at least 1 minute long")
    public boolean isTripTotalDurationValid() {
        if (startTime == null || endTime == null)
            return true;
        return Duration.between(startTime, endTime).toMinutes() >= 1;
    }

    /**
     * Validates that max speed is greater than or equal to average speed.
     * @return true if speed metrics are logically consistent
     */
    @AssertTrue(message = "Max speed must be greater than or equal to average speed")
    public boolean isMaxSpeedGreaterThanAverageSpeed() {
        if (averageSpeed == null || maxSpeed == null)
            return true;
        return maxSpeed.compareTo(averageSpeed) >= 0;
    }

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        Trip trip = (Trip) o;
        return getId() != null && Objects.equals(getId(), trip.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}