package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a registered user in the Best Bike Paths (BBP) system.
 * Users can record trips, create and update bike paths, and report obstacles on bike routes.
 */
@Entity
@Table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * The unique identifier for the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the user.
     * This field is required and cannot exceed 50 characters.
     */
    @Column(nullable = false, length = 50)
    @NotBlank(message = "Name is required")
    @Size(max = 50, message = "Name must not exceed 50 characters")
    private String name;

    /**
     * The last name of the user.
     * This field is required and cannot exceed 50 characters.
     */
    @Column(nullable = false, length = 50)
    @NotBlank(message = "Surname is required")
    @Size(max = 50, message = "Surname must not exceed 50 characters")
    private String surname;

    /**
     * The unique username used for authentication.
     * This field is required, must be unique across the system, and cannot exceed 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    @NotBlank(message = "Username is required")
    @Size(max = 50, message = "Username must not exceed 50 characters")
    private String username;

    /**
     * The email address of the user.
     * This field is required, must be unique, must follow a valid email format, and cannot exceed 150 characters.
     */
    @Column(nullable = false, unique = true, length = 150)
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    /**
     * The hashed password used for user authentication.
     * This field stores the encrypted password and is required.
     */
    @Column(nullable = false, length = 60)
    @NotBlank(message = "Password is required")
    @Size(max = 80, message = "Password must not exceed 60 characters")
    private String password;

    /**
     * The collection of cycling trips recorded by this user.
     * Each trip includes statistics such as distance, average speed, and other performance metrics.
     * When a user is deleted, all their recorded trips are automatically removed (cascade delete).
     */
    @OneToMany(mappedBy = "recordedBy", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Trip> recordedTrips = new ArrayList<>();

    /**
     * The collection of bike paths originally created by this user.
     * Users can insert bike path information either manually or through automated tracking.
     * When a user is deleted, all bike paths they created are automatically removed (cascade delete).
     */
    @OneToMany(mappedBy = "createdBy", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<BikePath> createdBikePaths = new ArrayList<>();

    /**
     * The collection of bike paths that were last updated by this user.
     * This relationship tracks the modification history of bike paths.
     * Updates to bike paths are preserved even if the user is deleted (no cascade delete).
     */
    @OneToMany(mappedBy = "updatedBy")
    @Builder.Default
    private List<BikePath> updatedBikePaths = new ArrayList<>();

    /**
     * The collection of obstacles originally reported by this user.
     * Obstacles include issues like potholes or other problems on bike paths.
     * When a user is deleted, the obstacles remain in the system with their creator reference set to null.
     */
    @OneToMany(mappedBy = "createdBy")
    @Builder.Default
    private List<Obstacle> createdObstacles = new ArrayList<>();

    /**
     * The collection of obstacles that were last updated by this user.
     * This relationship tracks the modification history of reported obstacles.
     * Updates to obstacles are preserved even if the user is deleted (no cascade delete).
     */
    @OneToMany(mappedBy = "updatedBy")
    @Builder.Default
    private List<Obstacle> updatedObstacles = new ArrayList<>();

}