package it.polimi.se.bbp.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.util.*;

/**
 * Entity representing a registered user in the system.
 * Users can record trips, create and update bike paths, and report obstacles.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"recordedTrips", "createdBikePaths", "updatedBikePaths", "createdObstacles", "updatedObstacles"})
public class User {

    /**
     * Unique identifier, auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_generator")
    @SequenceGenerator(name = "users_generator", sequenceName = "users_sequence", allocationSize = 1)
    private Long id;

    /**
     * First name of the user.
     * Maximum 50 characters.
     */
    @Column(nullable = false, length = 50)
    @NotBlank(message = "Name is required")
    @Size(max = 50, message = "Name must not exceed 50 characters")
    private String name;

    /**
     * Last name of the user.
     * Maximum 50 characters.
     */
    @Column(nullable = false, length = 50)
    @NotBlank(message = "Surname is required")
    @Size(max = 50, message = "Surname must not exceed 50 characters")
    private String surname;

    /**
     * Unique username for authentication.
     * Must be unique system-wide, maximum 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    @NotBlank(message = "Username is required")
    @Size(max = 50, message = "Username must not exceed 50 characters")
    private String username;

    /**
     * Email address.
     * Must be unique and valid, maximum 150 characters.
     */
    @Column(nullable = false, unique = true, length = 150)
    @NotBlank(message = "Email is required")
    @Size(max = 150, message = "Email must not exceed 150 characters")
    @Email(message = "Email must be valid")
    private String email;

    /**
     * Hashed password for authentication.
     * Stores encrypted password, maximum 60 characters (BCrypt).
     */
    @Column(nullable = false, length = 60)
    @NotBlank(message = "Password is required")
    @Size(max = 60, message = "Password must not exceed 60 characters")
    private String password;

    /**
     * Cycling trips recorded by this user.
     * Includes statistics like distance, average speed, and performance metrics.
     * Cascade delete: removed when user is deleted.
     */
    @OneToMany(mappedBy = "recordedBy", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("startTime DESC")
    @Builder.Default
    private List<Trip> recordedTrips = new ArrayList<>();

    /**
     * Bike paths originally created by this user.
     * Can be inserted manually or through automated tracking.
     * Cascade delete: removed when user is deleted.
     */
    @OneToMany(mappedBy = "createdBy", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("createdAt DESC")
    @Builder.Default
    private List<BikePath> createdBikePaths = new ArrayList<>();

    /**
     * Bike paths last updated by this user.
     * Tracks modification history, preserved when user is deleted.
     */
    @OneToMany(mappedBy = "updatedBy", fetch = FetchType.LAZY)
    @OrderBy("updatedAt DESC")
    @Builder.Default
    private List<BikePath> updatedBikePaths = new ArrayList<>();

    /**
     * Obstacles originally reported by this user.
     * Includes issues like potholes or other problems on bike paths.
     * Preserved when user is deleted (creator reference set to null).
     */
    @OneToMany(mappedBy = "createdBy", fetch = FetchType.LAZY)
    @OrderBy("createdAt DESC")
    @Builder.Default
    private List<Obstacle> createdObstacles = new ArrayList<>();

    /**
     * Obstacles last updated by this user.
     * Tracks modification history, preserved when user is deleted.
     */
    @OneToMany(mappedBy = "updatedBy", fetch = FetchType.LAZY)
    @OrderBy("updatedAt DESC")
    @Builder.Default
    private List<Obstacle> updatedObstacles = new ArrayList<>();

    /**
     * Adds a trip and synchronizes bidirectional relationship.
     * @param trip trip to add
     */
    public void addRecordedTrip(Trip trip) {
        if (this.recordedTrips == null) {
            this.recordedTrips = new ArrayList<>();
        }
        this.recordedTrips.add(trip);
        trip.setRecordedBy(this);
    }

    /**
     * Removes a trip and synchronizes bidirectional relationship.
     * @param trip trip to remove
     */
    public void removeRecordedTrip(Trip trip) {
        if (this.recordedTrips != null) {
            this.recordedTrips.remove(trip);
            trip.setRecordedBy(null);
        }
    }

    /**
     * Adds a bike path and synchronizes bidirectional relationship.
     * @param path bike path to add
     */
    public void addCreatedBikePath(BikePath path) {
        if (this.createdBikePaths == null) {
            this.createdBikePaths = new ArrayList<>();
        }
        this.createdBikePaths.add(path);
        path.setCreatedBy(this);
    }

    /**
     * Removes a bike path and synchronizes bidirectional relationship.
     * @param path bike path to remove
     */
    public void removeCreatedBikePath(BikePath path) {
        if (this.createdBikePaths != null) {
            this.createdBikePaths.remove(path);
            path.setCreatedBy(null);
        }
    }

    /**
     * Adds an obstacle and synchronizes bidirectional relationship.
     * @param obstacle obstacle to add
     */
    public void addCreatedObstacle(Obstacle obstacle) {
        if (this.createdObstacles == null) {
            this.createdObstacles = new ArrayList<>();
        }
        this.createdObstacles.add(obstacle);
        obstacle.setCreatedBy(this);
    }

    /**
     * Removes an obstacle and synchronizes bidirectional relationship.
     * @param obstacle obstacle to remove
     */
    public void removeCreatedObstacle(Obstacle obstacle) {
        if (this.createdObstacles != null) {
            this.createdObstacles.remove(obstacle);
            obstacle.setCreatedBy(null);
        }
    }

    /**
     * Checks equality based on database ID.
     * Handles Hibernate proxies properly.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass)
            return false;
        User user = (User) o;
        return getId() != null && Objects.equals(getId(), user.getId());
    }

    /**
     * Returns constant hash code for this entity.
     * Necessary because ID may not be available before persistence.
     */
    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

}